---
title: "check library size RAPseq"
author: Qun Li
date: 3 Sep 2024 ( 12:30:09 )
output:
  pdf_document: 
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r envs}
rm(list = ls())
setwd("/Users/liqun/Desktop/Projects/RAPseq/0_RAPSeq/")
```

```{r libraries}
library(ggplot2)
library(data.table)
```

```{r loaddata}
# 34514162 reads
read_length <- fread("../Data/Librarysize/read_lengths.txt")

read_length$Name <- "Input"
colnames(read_length) <- c("length", "Name")
```

```{r violinPlot}
p <- ggplot(read_length, aes(x=Name, y=length)) + 
  geom_violin(trim=FALSE, fill="grey", alpha=0.5) +
  geom_boxplot(width=0.1, fill="white", color="black", outlier.shape=NA) +
  coord_cartesian(ylim=c(0,150)) +
  theme_classic() +
  ylab("Input library insert size (nt)") +
  xlab("3.45x10**7 reads")

p
ggsave("../0_RAPSeq/inputLibrarySize.pdf", p, width = 3, height = 5)
```

```{r getSummaryofreadlengths}
summary(read_length$length)
```



```{bash readLengthsSummary}
# if your R cant load all read length files, so we use shell scripts to get read length summary information

sort -n read_lengths.txt | awk '{
  a[NR]=$1; sum+=$1
}
END {
  mean = sum/NR
  if (NR%2==1) {
    median = a[(NR+1)/2]
  } else {
    median = (a[NR/2] + a[NR/2+1])/2
  }
  q1 = a[int(NR*0.25)]
  q3 = a[int(NR*0.75)]
  iqr = q3 - q1
  print "Mean:", mean
  print "Median:", median
  print "Q1:", q1
  print "Q3:", q3
  print "IQR:", iqr
}'
```

```{bash output}
#Mean: 39.4285
#Median: 35
#Q1: 25
#Q3: 49
#IQR: 24
```
